(setf *initpsd* '((next-to goalie defenseman)
		  (next-to defenseman midfield)
		  (next-to midfield forward)
		  (next-to opgoalie opdefenseman)
		  (next-to opdefenseman opmidfield)
		  (next-to opmidfield opforward)
		  (matchup defenseman opforward)
		  (matchup midfield opmidfield)
		  (matchup forward opdefenseman)
		  (matchup opdefenseman forward)
		  (matchup opmidfield midfield)
		  (matchup opforward defenseman)
		  (guarded defenseman)
		  (not-guarded midfield)
		  (not-guarded forward)
		  (guarded opdefenseman)
		  (guarded opmidfield)
		  (guarded opforward)


		  (has-ball midfield))) 

(setf *gspec* '((not-guarded ?x) (not-guarded ?y)))
