;Clothes world

(setf *ops* '(
              ((put-on-sock ?x)
               ()
               ()
               ((sock-on ?x)))
              ((put-on-shoe ?x)
               ((sock-on ?x)(pants-on))
               ()
               ((shoe-on ?x)))
              ((put-on-shirt)
               ((underwear-on))
               ()
               ((shirt-on)))
              ((put-on-underwear)
               ((naked))
               ((naked))
               ((underwear-on)))
			  ((put-on-pants)
               ((underwear-on))
               ()
               ((pants-on)))
			  ((put-on-glove ?x)
               ((jacket-on))
               ()
               ((glove-on ?x)))
			  ((put-on-jacket)
               ((underwear-on)(shirt-on))
               ()
               ((jacket-on)(hot)))))